# Generated by Django 4.2 on 2023-04-23 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tutorial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("video_title", models.CharField(max_length=200)),
                ("video_content", models.TextField()),
                (
                    "tutorial_published",
                    models.DateTimeField(verbose_name="date published"),
                ),
            ],
        ),
    ]
