# Generated by Django 3.2.13 on 2023-04-24 13:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_video_video_published'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('art_title', models.CharField(max_length=200)),
                ('art_published', models.DateTimeField(default=datetime.datetime(2023, 4, 24, 14, 20, 10, 943866), verbose_name='date published')),
                ('art_image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.AlterField(
            model_name='video',
            name='video_published',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 24, 14, 20, 10, 943866), verbose_name='date published'),
        ),
    ]
