# Generated by Django 3.2.13 on 2023-04-24 17:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20230424_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='art_published',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 24, 18, 21, 52, 534490), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_published',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 24, 18, 21, 52, 534490), verbose_name='date published'),
        ),
    ]
