# Generated by Django 3.2 on 2023-04-30 22:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20230424_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='art_image',
            field=models.ImageField(upload_to='main/static/main/images/artwork'),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='art_published',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 30, 23, 33, 11, 189624), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_published',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 30, 23, 33, 11, 189624), verbose_name='date published'),
        ),
    ]
